version: "3.7"

services:
  runtests:
    image: goyalzz/ubuntu-java-8-maven-docker-image
    volumes:
      - ./m2:/root/.m2
      - ./entrypoint.sh:/entrypoint.sh
    command:
      - ./entrypoint.sh

